apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"

aliases:
  - &host_rule
    host: multi-k8s
    http:
      paths:
        - path: /?(.*)
          backend:
            serviceName: client-cluster-ip-service
            servicePort: 3000
        - path: /api/?(.*)
          backend:
            serviceName: server-cluster-ip-service
            servicePort: 5000

spec:
  tls:
    - hosts:
        - san-ng.dev
        - www.san-ng.dev
      secretName: san-ng-dev
  rules:
    - <<: *host_rule
      host: san-ng.dev
    - <<: *host_rule
      host: www.san-ng.dev
