### client-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment-__BRANCH_NAME__
spec:
  replicas: __CLIENT_REPLICAS__
  selector:
    matchLabels:
      component: web-__BRANCH_NAME__
  template:
    metadata:
      labels:
        component: web-__BRANCH_NAME__
    spec:
      containers:
        - name: client
          image: asia.gcr.io/__PROJECT_ID__/multi-client:__SHORT_SHA__
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service-__BRANCH_NAME__
spec:
  type: ClusterIP
  selector:
    component: web-__BRANCH_NAME__
  ports:
    - port: 3000
      targetPort: 3000

### server-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment-__BRANCH_NAME__
spec:
  replicas: __SERVER_REPLICAS__
  selector:
    matchLabels:
      component: server-__BRANCH_NAME__
  template:
    metadata:
      labels:
        component: server-__BRANCH_NAME__
    spec:
      containers:
        - name: server
          image: asia.gcr.io/__PROJECT_ID__/multi-server:__SHORT_SHA__
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service-__BRANCH_NAME__
spec:
  type: ClusterIP
  selector:
    component: server-__BRANCH_NAME__
  ports:
    - port: 5000
      targetPort: 5000

### worker-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment-__BRANCH_NAME__
spec:
  replicas: __WORKER_REPLICAS__
  selector:
    matchLabels:
      component: worker-__BRANCH_NAME__
  template:
    metadata:
      labels:
        component: worker-__BRANCH_NAME__
    spec:
      containers:
        - name: worker
          image: asia.gcr.io/__PROJECT_ID__/multi-worker:__SHORT_SHA__
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIST_PORT
              value: '6379'
